# Generated by Django 2.2.1 on 2019-05-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=85)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('production', 'Production'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10)),
            ],
        ),
    ]
